[workspace]
resolver = "2"
members = [
    "crates/crypto",
    "crates/vault",
    "crates/event-policy",
    "crates/permissions",
    "crates/protocol",
    "crates/signer-core",
    "crates/cli",
    "apps/tauri/desktop/src-tauri",
    "platform/desktop-native-messaging/host",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "LGPL-3.0-or-later"
